#!/usr/bin/env python3
"""Merge NotchPet custom en->zh-Hans pairs into Localizable.xcstrings.

Only ADDS a zh-Hans translation when the key is missing entirely or lacks zh-Hans;
never overwrites an existing zh-Hans value (so the 492 upstream translations are kept).
"""
import json, sys, os

CATALOG = os.path.join(os.path.dirname(__file__), "..", "boringNotch", "Localizable.xcstrings")

# Static UI strings (no interpolation). en key -> Simplified Chinese.
STATIC = {
    # --- Music / lyrics ---
    "Default music app": "默认音乐应用",
    "Opened from the album-art button when nothing is playing.": "无播放时，点击专辑封面按钮打开它。",
    "Show lyrics below the notch": "在刘海下方显示歌词",
    "Hide lyrics below the notch": "隐藏刘海下方的歌词",
    # --- AI coding / agent sync ---
    "AI Coding": "AI 编码",
    "AI sync is off.": "AI 同步已关闭。",
    "Enable": "启用",
    "No active agents. Start a task in Claude Code.": "暂无活动对话。请在 Claude Code 中启动任务。",
    "Done": "完成",
    "Error": "错误",
    "Needs you": "需要你",
    "Working": "工作中",
    "Idle": "空闲",
    "Thinking": "思考中",
    "Subagents": "子代理",
    "Compacting": "压缩中",
    "Asleep": "休眠",
    "AI Agent Sync": "AI 对话同步",
    "Enable agent sync": "启用对话同步",
    "The notch and desktop pet react to Claude Code (and compatible CLIs) in real time — and tell you when a long task finishes.": "刘海和桌面宠物会实时响应 Claude Code（及兼容的命令行工具），并在长任务完成时通知你。",
    "Claude Code hooks": "Claude Code 钩子",
    "Hooks installed": "钩子已安装",
    "Hooks not installed": "钩子未安装",
    "Install / Repair": "安装 / 修复",
    "Remove": "移除",
    "Hooks are merged into ~/.claude/settings.json (your own hooks are preserved).": "钩子将合并到 ~/.claude/settings.json（保留你自己的钩子）。",
    "Notifications": "通知",
    "System notification on completion": "完成时发送系统通知",
    "Play sound": "播放声音",
    "Show status in closed notch": "在收起的刘海中显示状态",
    "Coding tools": "编码工具",
    "NotchPet reuses clawd-on-desk's ready-made installers to capture tasks from many CLIs/IDEs. Toggle which to hook.": "NotchPet 复用 clawd-on-desk 现成的安装程序，以捕获来自多种命令行工具/IDE 的任务。选择要接入的工具。",
    "Reinstall all tool hooks": "重新安装所有工具钩子",
    "Permissions (advanced)": "权限（高级）",
    "Answer permission requests in NotchPet": "在 NotchPet 中响应权限请求",
    "When on, tool-permission prompts appear as a bubble. When off, Claude Code keeps using its own terminal prompt.": "开启后，工具权限提示会以气泡形式出现。关闭后，Claude Code 将继续使用其自带的终端提示。",
    "Auto-pilot: approve all requests": "自动驾驶：批准所有请求",
    "Auto-pilot": "自动驾驶",
    "Turn off auto-pilot": "关闭自动驾驶",
    "Turn on auto-pilot": "开启自动驾驶",
    "Session only. Automatically approves commands, file changes, and clarification prompts; it turns off when NotchPet quits.": "仅本次会话有效。自动批准命令、文件更改和澄清问题；退出 NotchPet 后自动关闭。",
    "ChatGPT/Codex desktop tasks keep using the permission mode selected in ChatGPT; their log monitor exposes status, but not an approval response channel.": "ChatGPT/Codex 桌面任务仍使用 ChatGPT 中选择的权限模式；日志监控能读取状态，但不提供授权响应通道。",
    "Turn on auto-pilot?": "要开启自动驾驶吗？",
    "Enable auto-pilot for this session": "为本次会话开启自动驾驶",
    "All interactive task requests may be approved without review, including shell commands and file deletion. Background/subagent requests remain excluded.": "所有交互式任务请求都可能未经审查直接批准，包括终端命令和文件删除。后台任务和子代理请求仍会排除。",
    "Cancel": "取消",
    "Reinstalling hooks…": "正在重新安装钩子…",
    "Hooks reinstalled (self-contained — no clawd app needed).": "钩子已重新安装（独立运行，无需 clawd 应用）。",
    "Task finished.": "任务已完成。",
    "Needs your input.": "需要你的输入。",
    "Could not write hook script (helper unavailable).": "无法写入钩子脚本（辅助进程不可用）。",
    "Could not serialize settings.": "无法序列化设置。",
    "Could not write settings.json.": "无法写入 settings.json。",
    "Nothing to remove.": "无需移除。",
    "Removed NotchPet hooks.": "已移除 NotchPet 钩子。",
    "Permission request": "权限请求",
    "Deny": "拒绝",
    "Allow": "允许",
    "Needs your answer": "需要你回答",
    "Go to terminal": "前往终端",
    "Previous": "上一个",
    "Submit": "提交",
    "Next": "下一个",
    "Or type your own…": "或自己输入…",
    "Please review and approve the plan": "请审阅并批准计划",
    "Asking you a question (AskUserQuestion)": "正在向你提问 (AskUserQuestion)",
    # --- Launcher ---
    "Applications": "应用程序",
    "Search": "搜索",
    "Refresh": "刷新",
    "Add app…": "添加应用…",
    "Frequently used": "常用",
    "All": "全部",
    "Productivity & Finance": "效率与财务",
    "Developer Tools": "开发者工具",
    "Social": "社交",
    "Utilities": "工具",
    "Entertainment": "娱乐",
    "Creativity": "创意",
    "Other": "其他",
    "Loading apps…": "正在加载应用…",
    "No apps in this category": "此类别中没有应用",
    "Show app names under icons": "在图标下显示应用名称",
    "No favorite apps yet": "暂无收藏的应用",
    "Favorite Apps": "收藏的应用",
    "Add to Launcher": "添加到启动器",
    "Add": "添加",
    "Choose one or more applications to add to your launcher.": "选择一个或多个应用添加到你的启动器。",
    # --- Home widgets ---
    "Clock": "时钟",
    "Music": "音乐",
    "No widgets": "暂无小组件",
    "Add widgets in Settings → Home Widgets": "在“设置 → 主页小组件”中添加小组件",
    "All clear ✓": "全部完成 ✓",
    "Charging": "充电中",
    "Low Power": "低电量模式",
    "Plugged": "已接通电源",
    "No widgets enabled": "未启用任何小组件",
    "The Home page shows these widget cards, scrollable left-to-right.": "主页会显示这些小组件卡片，可左右滑动。",
    "Widgets": "小组件",
    "Toggle which widgets show on the Home page; drag to reorder them.": "切换主页显示的小组件；拖动可重新排序。",
    # --- Quick actions ---
    "Quick Actions": "快捷操作",
    "No actions enabled": "未启用任何操作",
    "Enable actions in Settings.": "在设置中启用操作。",
    "Actions": "操作",
    "Toggle which actions appear in the grid. Drag to reorder. All actions are sandbox-safe and open System Settings panes or built-in tools.": "切换网格中显示的操作。拖动可重新排序。所有操作均在沙盒中安全运行，会打开系统设置面板或内置工具。",
    "Displays": "显示器",
    "Sound": "声音",
    "Bluetooth": "蓝牙",
    "Network": "网络",
    "Focus": "专注",
    "Mission Control": "调度中心",
    "Open Mission Control": "打开调度中心",
    "Launchpad": "启动台",
    "Open Launchpad": "打开启动台",
    "Screenshot": "截屏",
    "Open the Screenshot tool": "打开截屏工具",
    # --- Lyrics ---
    "Fetching lyrics…": "正在获取歌词…",
    "No lyrics available": "暂无歌词",
    "No lyrics found": "未找到歌词",
    "Lyrics are turned off": "歌词已关闭",
    "Enable lyrics in Settings to see them here.": "在设置中启用歌词后即可在此查看。",
    # --- Photos ---
    "Photos": "照片",
    "Change folder": "更换文件夹",
    "No photo folder selected": "未选择照片文件夹",
    "Choose folder…": "选择文件夹…",
    "Loading photos…": "正在加载照片…",
    "No images in this folder": "此文件夹中没有图片",
    "Choose another…": "选择其他文件夹…",
    "Source Folder": "源文件夹",
    "Access lost — please re-select": "访问权限已失效 — 请重新选择",
    "No folder selected": "未选择文件夹",
    "Choose Folder…": "选择文件夹…",
    "Clear": "清除",
    "Include sub-folders": "包含子文件夹",
    "Thumbnail size": "缩略图大小",
    "Images found": "找到的图片",
    "Choose": "选择",
    "Choose a Photo Folder": "选择照片文件夹",
    "Select a folder containing images to browse in the notch.": "选择一个包含图片的文件夹，以便在刘海中浏览。",
    "Lost access to the saved folder. Please choose it again.": "已失去对已保存文件夹的访问权限。请重新选择。",
    # --- Pomodoro ---
    "Paused": "已暂停",
    "Pause": "暂停",
    "Start": "开始",
    "Resume": "继续",
    "Skip phase": "跳过阶段",
    "Reset": "重置",
    "Focus sessions until a long break": "长休息前的专注次数",
    "Ready": "就绪",
    "Short Break": "短休息",
    "Long Break": "长休息",
    "Focus complete": "专注完成",
    "Nice work. Time for a break.": "干得好，该休息一下了。",
    "Break over": "休息结束",
    "Back to focus.": "回到专注。",
    "Long break over": "长休息结束",
    "Ready for the next round?": "准备好下一轮了吗？",
    "Durations": "时长",
    "Short break": "短休息",
    "Long break": "长休息",
    "Long break after": "长休息间隔",
    "Behavior": "行为",
    "Auto-start next phase": "自动开始下一阶段",
    "Play sound on completion": "完成时播放声音",
    "Show in closed notch while running": "运行时在收起的刘海中显示",
    # --- To-Do ---
    "Hide completed": "隐藏已完成",
    "Show completed": "显示已完成",
    "Clear completed": "清除已完成",
    "Add a task…": "添加任务…",
    "No tasks yet": "暂无任务",
    "Nothing to do": "没有待办事项",
    "Type above and press return": "在上方输入并按回车",
    "Delete task": "删除任务",
    "Mark as not done": "标记为未完成",
    "Mark as done": "标记为已完成",
    "Delete": "删除",
    "Today": "今天",
    "Tomorrow": "明天",
    "Manual": "手动",
    "Newest first": "最新优先",
    "Oldest first": "最早优先",
    "Due date": "截止日期",
    "To-Do due": "待办到期",
    "Show completed tasks": "显示已完成任务",
    "Default sort": "默认排序",
    "List": "列表",
    "Manual order lets you arrange tasks yourself; new tasks appear at the top.": "手动排序可让你自行排列任务；新任务显示在顶部。",
    "Reordering is only available with Manual sort.": "仅在手动排序时可重新排序。",
    "Open tasks": "未完成任务",
    "Total tasks": "任务总数",
    "Clear completed tasks": "清除已完成任务",
    "Maintenance": "维护",
    # --- Notes ---
    "New note": "新建便签",
    "Delete selected note": "删除所选便签",
    "No notes yet": "暂无便签",
    "Create one": "创建一个",
    "Select or create a note": "选择或创建便签",
    "Type your note…": "输入便签内容…",
    "New Note": "新便签",
    "Editor": "编辑器",
    "Font Size": "字号",
    "Monospaced Font": "等宽字体",
    "The quick brown fox jumps over the lazy dog.": "敏捷的棕色狐狸跳过懒狗。",
    "Hourly": "每小时",
    "Daily": "每日",
    # --- Weather ---
    "Refresh weather": "刷新天气",
    "Loading weather…": "正在加载天气…",
    "Try again": "重试",
    "Now": "现在",
    "No connection": "无网络连接",
    "Couldn't load weather": "无法加载天气",
    "Manual Location": "手动位置",
    "Current Location": "当前位置",
    "Celsius": "摄氏度",
    "Fahrenheit": "华氏度",
    "Mainly Clear": "大致晴朗",
    "Partly Cloudy": "局部多云",
    "Overcast": "阴",
    "Fog": "雾",
    "Light Drizzle": "小毛毛雨",
    "Drizzle": "毛毛雨",
    "Heavy Drizzle": "大毛毛雨",
    "Freezing Drizzle": "冻毛毛雨",
    "Light Rain": "小雨",
    "Rain": "雨",
    "Heavy Rain": "大雨",
    "Freezing Rain": "冻雨",
    "Light Snow": "小雪",
    "Snow": "雪",
    "Heavy Snow": "大雪",
    "Snow Grains": "米雪",
    "Light Showers": "小阵雨",
    "Showers": "阵雨",
    "Heavy Showers": "大阵雨",
    "Snow Showers": "阵雪",
    "Thunderstorm": "雷暴",
    "Thunderstorm, Hail": "雷暴伴冰雹",
    "Unknown": "未知",
    "Units": "单位",
    "Temperature": "温度",
    "Celsius (°C)": "摄氏度 (°C)",
    "Fahrenheit (°F)": "华氏度 (°F)",
    "Use my location": "使用我的位置",
    "Location": "位置",
    "When location access is off or denied, the manual city below is used instead.": "当位置访问关闭或被拒绝时，将改用下方的手动城市。",
    "City name": "城市名称",
    "Latitude": "纬度",
    "Longitude": "经度",
    "Save manual city": "保存手动城市",
    "Manual City": "手动城市",
    "Enter coordinates between -90…90 (latitude) and -180…180 (longitude). Used as a fallback for weather data.": "请输入纬度 -90…90 和经度 -180…180 之间的坐标。用作天气数据的备用位置。",
    "Refresh now": "立即刷新",
    "Location access granted": "已授予位置访问权限",
    "Location denied — using manual city. Enable in System Settings › Privacy.": "位置被拒绝 — 使用手动城市。请在系统设置 › 隐私中启用。",
    "Location restricted — using manual city.": "位置受限 — 使用手动城市。",
    "Location permission will be requested when the Weather tab opens.": "打开天气标签页时将请求位置权限。",
    "Location status unknown — using manual city.": "位置状态未知 — 使用手动城市。",
    # --- Reminders ---
    "Water": "喝水",
    "Posture": "久坐",
    "Sleep": "睡眠",
    "Water reminder": "喝水提醒",
    "Every": "每隔",
    "Hydration": "补水",
    "Nudges you to drink water during your active hours.": "在你的活跃时段提醒你喝水。",
    "Posture reminder": "久坐提醒",
    "Sedentary": "久坐",
    "Reminds you to stand up and move after sitting too long.": "久坐过久后提醒你起身活动。",
    "Sleep reminder": "睡眠提醒",
    "Time": "时间",
    "Bedtime": "就寝时间",
    "A one-time nudge each day to wind down. Not affected by quiet hours.": "每天一次提醒你放松休息。不受勿扰时段影响。",
    "Active from": "活跃时段从",
    "until": "至",
    "Quiet hours": "勿扰时段",
    "Water & posture reminders only fire inside this window. Outside it (your quiet hours) they stay silent. The window may cross midnight.": "喝水和久坐提醒仅在此时段内触发。在此时段之外（你的勿扰时段）保持静默。该时段可跨越午夜。",
    "Time to drink water": "喝水提醒",
    "Time to move": "久坐提醒",
    "Bedtime reminder": "睡眠提醒",
    "Get up and drink some water to stay hydrated 💧": "起来喝口水，给身体补充水分 💧",
    "You've been sitting a while — stand up and move around 🧍": "你已经坐了一会儿，站起来活动一下 🧍",
    "Time to wind down — an early night is good for you 😴": "该准备休息了，早睡身体好 😴",
    # --- Settings: sidebar / general / NotchPet section ---
    "Components": "组件",
    "Home Widgets": "主页小组件",
    "AI Agents": "AI 智能体",
    "Reminders": "提醒",
    "Launcher": "启动台",
    "Language": "语言",
    "Follow system": "跟随系统",
    "Preview": "预览",
    "Agents": "智能体",
    "Lyrics": "歌词",
    "Edit layout": "编辑布局",
    "Close": "关闭",
    "Reset to Defaults": "恢复默认值",
    "Clear slot": "清除槽位",
    "Layout Preview": "布局预览",
    "Drag items in the preview to reorder or drop from the palette": "在预览中拖动项目以重新排序，或从调色板中拖放",
    "Drag a control onto a slot": "将控件拖到槽位上",
    "Choose which components appear as tabs in the expanded notch, and drag to reorder. Up to 12 fit around the notch (6 left + 6 right) without scrolling.": "选择哪些组件显示为展开刘海中的标签页，并拖动以重新排序。刘海周围最多可容纳 12 个（左 6 + 右 6）无需滚动。",
    "Tabs in use": "已使用的标签页",
    "More than 12 enabled — tabs past 12 won't be shown.": "已启用超过 12 个 — 超出 12 个的标签页将不会显示。",
    "Home is always shown first as the default page. Drag handles reorder; the order also controls which side of the notch each tab lands on.": "主页始终作为默认页面首先显示。拖动手柄可重新排序；该顺序也决定每个标签页落在刘海的哪一侧。",
    # --- second pass: gaps the scanner found ---
    "Launch at login": "登录时启动",
    "Player tinting": "播放器着色",
    "Drop on notch starts AirDrop": "拖放到刘海启动隔空投送",
    "Choose between your system accent color or customize it with your own selection.": "在系统强调色和你自己的自定义选择之间进行选择。",
    # Quick-action per-pane help tooltips (built as "Open <title> settings").
    "Open Displays settings": "打开显示器设置",
    "Open Sound settings": "打开声音设置",
    "Open Bluetooth settings": "打开蓝牙设置",
    "Open Network settings": "打开网络设置",
    "Open Wi-Fi settings": "打开 Wi-Fi 设置",
    "Open Battery settings": "打开电池设置",
    "Open Notifications settings": "打开通知设置",
    "Open Focus settings": "打开专注设置",
    "Open Appearance settings": "打开外观设置",
}

# Interpolated / format keys — SwiftUI/String(localized:) generate %lld (Int), %@ (String).
INTERP = {
    "port %lld": "端口 %lld",
    "AI agent: %@": "AI 对话：%@",
    "Asking you a question (%@)": "正在向你提问 (%@)",
    "· %@%% left": "· 剩 %@%%",
    "%lld today": "今日 %lld 次",
    "%lld min": "%lld 分钟",
    "%lld sessions": "%lld 次",
    "%lld left": "剩余 %lld",
    "Every %lld minutes": "每 %lld 分钟",
    "Open %@ settings": "打开 %@ 设置",
    "Installed (%lld new hook entries).": "已安装（%lld 个新钩子条目）。",
    "Feels %@": "体感 %@",
    "Currently selected: %@": "当前选择：%@",
    "Max Capacity: %lld%%": "最大容量：%lld%%",
    "Time to Full Charge: %lld min": "充满需时：%lld 分钟",
}

# Upstream keys whose zh-Hans value is just the English text (untranslated stubs). These DO have a
# zh-Hans entry, so they were skipped before; the merge now overwrites a stub with these.
STUBS = {
    "Accessibility access is required to replace the system HUD.": "替换系统 HUD 需要辅助功能权限。",
    "Advanced": "高级",
    "Always show full event titles": "始终显示完整事件标题",
    "Auto-scroll to next event": "自动滚动到下一个事件",
    "Change media with horizontal gestures": "用水平手势切换媒体",
    "Choose any color": "选择任意颜色",
    "Choose which service to use when sharing files from the shelf. Click the shelf button to select files, or drag files onto it to share immediately.": "选择从搁架分享文件时使用的服务。点击搁架按钮选择文件，或将文件拖放到上面立即分享。",
    "Clear slot": "清除槽位",
    "Closed Notch": "关闭的刘海",
    "Color Presets": "颜色预设",
    "Colored spectrogram": "彩色频谱图",
    "Copy items on drag": "拖动时复制项目",
    "Custom": "自定义",
    "Customize which controls appear in the music player. Volume expands when active.": "自定义音乐播放器中显示的控制项。音量在激活时展开。",
    "Drag a control onto a slot": "将控件拖到槽位上",
    "Drag items in the preview to reorder or drop from the palette": "在预览中拖动项目以重新排序，或从调色板中拖放",
    "Enable haptic feedback": "启用触感反馈",
    "Expanded drag detection area": "扩大拖放检测区域",
    "Files dropped on the shelf will be shared via this service": "拖放到搁架的文件将通过此服务分享",
    "Full screen behavior": "全屏行为",
    "Hide all-day events": "隐藏全天事件",
    "Hide for all apps": "对所有应用隐藏",
    "Hide for media app only": "仅对媒体应用隐藏",
    "Hide from screen recording": "从屏幕录制中隐藏",
    "Hide title bar": "隐藏标题栏",
    "Hover delay": "悬停延迟",
    "Layout Preview": "布局预览",
    "Match menu bar height": "匹配菜单栏高度",
    "Match real notch height": "匹配真实刘海高度",
    "Muted": "已静音",
    "No events": "暂无事件",
    "Notch height on non-notch displays": "非刘海屏的刘海高度",
    "Notch height on notch displays": "刘海屏的刘海高度",
    "Notch sizing": "刘海尺寸",
    "Open Notch": "打开的刘海",
    "Option key behaviour": "Option 键行为",
    "Pick a Color": "选取颜色",
    "Preferred display": "首选显示器",
    "Progress bar style": "进度条样式",
    "Quick Share": "快速分享",
    "Quick Share Service": "快速分享服务",
    "Remove from shelf after dragging": "拖动后从搁架移除",
    "Replace system HUD": "替换系统 HUD",
    "Replaces the standard macOS volume, display brightness, and keyboard brightness HUDs with a custom design.": "用自定义设计替换标准的 macOS 音量、屏幕亮度和键盘亮度 HUD。",
    "Request Accessibility": "请求辅助功能权限",
    "Reset to Defaults": "恢复默认值",
    "Show HUD in open notch": "在打开的刘海中显示 HUD",
    "Show cool face animation while inactive": "闲置时显示酷炫面部动画",
    "Show lyrics below artist name": "在艺人名称下方显示歌词",
    "Show menu bar icon": "显示菜单栏图标",
    "Show music live activity": "显示音乐实时活动",
    "Show notch on lock screen": "在锁定屏幕上显示刘海",
    "Show percentage": "显示百分比",
    "Show settings icon in notch": "在刘海中显示设置图标",
    "Show sneak peek on playback changes": "播放变化时显示抢先预览",
    "System": "系统",
    "Tint progress bar with accent color": "用强调色为进度条着色",
    "Unmuted": "已取消静音",
    "Use your macOS system accent color": "使用你的 macOS 系统强调色",
    "Using System Accent": "使用系统强调色",
    "Window Appearance": "窗口外观",
    "Window Behavior": "窗口行为",
    "Your macOS system accent color": "你的 macOS 系统强调色",
}

def main():
    with open(CATALOG, "r", encoding="utf-8") as f:
        cat = json.load(f)
    strings = cat["strings"]
    added, skipped, filled = 0, 0, 0
    pairs = dict(STATIC); pairs.update(INTERP); pairs.update(STUBS)
    for en, zh in pairs.items():
        entry = strings.get(en)
        if entry is None:
            strings[en] = {"localizations": {"zh-Hans": {"stringUnit": {"state": "translated", "value": zh}}}}
            added += 1
        else:
            locs = entry.setdefault("localizations", {})
            existing = locs.get("zh-Hans", {}).get("stringUnit", {}).get("value")
            # Keep a real translation; overwrite only when missing OR it's an English stub (== key).
            if existing and existing != en:
                skipped += 1
            else:
                locs["zh-Hans"] = {"stringUnit": {"state": "translated", "value": zh}}
                filled += 1
    # Sort keys to keep the catalog stable/diff-friendly.
    cat["strings"] = {k: strings[k] for k in sorted(strings.keys())}
    with open(CATALOG, "w", encoding="utf-8") as f:
        json.dump(cat, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"added={added} filled={filled} skipped(existing)={skipped} total_pairs={len(pairs)}")

if __name__ == "__main__":
    main()
